services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: ${DOCKER_TARGET_REGISTRY}/homban.api:latest
    environment:
      - Credentials__Username=${HOMBAN_USER}
      - Credentials__Password=${HOMBAN_PASSWORD}
      - JwtSigningKey=${HOMBAN_JWT_KEY}
    volumes:
      - "${DATA_DIRECTORY}:/data"
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    image: ${DOCKER_TARGET_REGISTRY}/homban.react:latest
  rp:
    build:
      context: .
      dockerfile: Dockerfile.rp
    image: ${DOCKER_TARGET_REGISTRY}/homban.rp:latest
    depends_on:
      - api
      - react
    ports:
      - "8443:443"
    volumes:
      - "${CERTS_DIRECTORY}:/certs"


