services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: ${DOCKER_TARGET_REGISTRY}/homban.api:latest
    depends_on:
      - loki
    environment:
      - Credentials__Username=${HOMBAN_USER}
      - Credentials__Password=${HOMBAN_PASSWORD}
      - JwtSigningKey=${HOMBAN_JWT_KEY}
      - LokiSink=${LOKI_SINK_ENDPOINT}
    volumes:
      - "${DATA_DIRECTORY}:/data"
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    image: ${DOCKER_TARGET_REGISTRY}/homban.react:latest
  rp:
    build:
      context: .
      dockerfile: Dockerfile.rp
    image: ${DOCKER_TARGET_REGISTRY}/homban.rp:latest
    depends_on:
      - api
      - react
    ports:
      - "8443:443"
    volumes:
      - "${CERTS_DIRECTORY}:/certs"
  loki:
    image: grafana/loki:2.6.1
    # ports:
    #   - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - "${LOKI_DATA_DIRECTORY}:/loki"

  grafana:
    image: grafana/grafana:9.3.2
    ports:
      - "3000:3000"
    volumes:
      - "${GRAFANA_DATA_DIRECTORY}:/var/lib/grafana"
